/* auto-generated by OHOS-RS */
/* eslint-disable */

export declare function backendSummary(): string

export declare function buildMarker(): string

export declare function healthcheck(): string

export declare function controlledServerStart(configJson: string): string
export declare function controlledServerStop(): string
export declare function controlledServerGetStatus(): string
export declare function controlledIncomingPoll(limit: number): string
export declare function controlledIncomingResolve(requestId: string, accepted: boolean): string
export declare function controlledIncomingSetPermission(requestId: string, permission: string, enabled: boolean): string
export declare function controlledPasswordGet(): string
export declare function controlledPasswordRefresh(): string
export declare function controlledPasswordSetPermanent(password: string): string
export declare function controlledPasswordSetVerificationMethod(method: string): string
export declare function controlledSettingsGet(): string
export declare function controlledSettingSet(key: string, value: string): string
export declare function controlledTwoFactorGet(): string
export declare function controlledTwoFactorBegin(): string
export declare function controlledTwoFactorVerify(code: string): string
export declare function controlledTwoFactorDisable(): string
export declare function controlledTwoFactorRemoveTrustedDevices(hwidsJson: string): string
export declare function controlledTwoFactorClearTrustedDevices(): string
export declare function controlledScreenConfigure(configJson: string): string
export declare function controlledScreenCaptureStart(configJson: string): string
export declare function controlledScreenCaptureStop(): string
export declare function controlledScreenCaptureGetStatus(): string

export declare function inputInterceptorPollEvents(limit: number): string

export declare function inputInterceptorStart(): string

export declare function inputInterceptorStop(): string

export declare function mainAudioSupportLoopback(): boolean

export declare function mainCheckHwcodec(): void

export declare function mainCheckMouseTime(): void

export declare function mainCheckSuperUserPermission(): boolean

export declare function mainClearTrustedDevices(): void

export declare function mainCreateShortcut(id: string): void

export declare function mainCurrentIsWayland(): boolean

export declare function mainDefaultPrivacyModeImpl(): string

export declare function mainForgetPassword(id: string): void

export declare function mainGenerate2Fa(): string

export declare function mainGetApiServer(): string

export declare function mainGetAppName(): string

export declare function mainGetAsyncStatus(): string

export declare function mainGetBuildDate(): string

export declare function mainGetBuildinOption(key: string): string

export declare function mainGetCommon(key: string): string

export declare function mainGetCommonSync(key: string): string

export declare function mainGetConnectStatus(): string

export declare function mainGetDisplays(): string

export declare function mainGetError(): string

export declare function mainGetFav(): Array<string>

export declare function mainGetFingerprint(): string

export declare function mainGetHardOption(key: string): string

export declare function mainGetHomeDir(): string

export declare function mainGetLanPeers(): string

export declare function mainGetLangs(): string

export declare function mainGetLastRemoteId(): string

export declare function mainGetLicense(): string

export declare function mainGetLocalOption(key: string): string

export declare function mainGetLoginDeviceInfo(): string

export declare function mainGetMainDisplay(): string

export declare function mainGetMouseTime(): number

export declare function mainGetMyId(): string

export declare function mainGetNewStoredPeers(): string

export declare function mainGetNewVersion(): string

export declare function mainGetOption(key: string): string

export declare function mainGetOptions(): string

export declare function mainGetPeerFlutterOptionSync(id: string, key: string): string

export declare function mainGetPeerOption(id: string, key: string): string

export declare function mainGetPeerOptionSync(id: string, key: string): string

export declare function mainGetPeerSync(id: string): string

export declare function mainGetPrinterNames(): string

export declare function mainGetProxyStatus(): boolean

export declare function mainGetSocks(): Array<string>

export declare function mainGetSoftwareUpdateUrl(): void

export declare function mainGetSoundInputs(): Array<string>

export declare function mainGetTemporaryPassword(): string

export declare function mainGetTrustedDevices(): string

export declare function mainGetUnlockPin(): string

export declare function mainGetUseTextureRender(): boolean

export declare function mainGetUserDefaultOption(key: string): string

export declare function mainGetUuid(): string

export declare function mainGetVersion(): string

export declare function mainGotoInstall(): boolean

export declare function mainHandleRelayId(id: string): string

export declare function mainHasFileClipboard(): boolean

export declare function mainHasGpuTextureRender(): boolean

export declare function mainHasHwcodec(): boolean

export declare function mainHasValid2FaSync(): boolean

export declare function mainHasValidBotSync(): boolean

export declare function mainHasVram(): boolean

export declare function mainHideDock(): boolean

export declare function mainInitInputSource(): void

export declare function mainIsCanInputMonitoring(prompt: boolean): boolean

export declare function mainIsCanScreenRecording(prompt: boolean): boolean

export declare function mainIsInstalled(): boolean

export declare function mainIsInstalledDaemon(prompt: boolean): boolean

export declare function mainIsInstalledLowerVersion(): boolean

export declare function mainIsLoginWayland(): boolean

export declare function mainIsOptionFixed(key: string): boolean

export declare function mainIsProcessTrusted(prompt: boolean): boolean

export declare function mainIsShareRdp(): boolean

export declare function mainLoadFavPeers(): void

export declare function mainLoadLanPeers(): void

export declare function mainLoadRecentPeers(): void

export declare function mainLoadRecentPeersForAb(filter: string): string

export declare function mainMaxEncryptLen(): number

export declare function mainPeerExists(id: string): boolean

export declare function mainPeerHasPassword(id: string): boolean

export declare function mainRemovePeer(id: string): void

export declare function mainRemoveTrustedDevices(json: string): void

export declare function mainSetCommon(key: string, value: string): void

export declare function mainSetLocalOption(key: string, value: string): void

export declare function mainSetOption(key: string, value: string): void

export declare function mainSetOptions(json: string): void

export declare function mainSetPeerAlias(id: string, alias: string): void

export declare function mainSetPeerFlutterOptionSync(id: string, key: string, value: string): void

export declare function mainSetPeerOption(id: string, key: string, value: string): void

export declare function mainSetPeerOptionSync(id: string, key: string, value: string): boolean

export declare function mainSetShareRdp(enable: boolean): void

export declare function mainSetUnlockPin(pin: string): string

export declare function mainSetUserDefaultOption(key: string, value: string): void

export declare function mainStoreFav(favs: Array<string>): void

export declare function mainSupportRemoveWallpaper(): boolean

export declare function mainSupportedHwdecodings(): string

export declare function mainSupportedInputSource(): string

export declare function mainSupportedPrivacyModeImpls(): string

export declare function mainUpdateMe(): boolean

export declare function mainUpdateTemporaryPassword(): void

export declare function mainVerify2Fa(code: string): boolean

export declare function mainVerifyBot(token: string): string

export declare function mainWol(id: string): void

export declare function nativeVersion(): string

export declare function runtimeGetApiServer(): string

export declare function runtimeGetAccountState(): string

export declare function runtimeGetAccountLoginOptions(): string

export declare function runtimeStartAccountLoginOptions(): string

export declare function runtimePollAccountLoginOptions(): string

export declare function runtimeStartAccountLogin(payloadJson: string): string

export declare function runtimeStartAccountOidc(provider: string): string

export declare function runtimePollAccountOidc(): string

export declare function runtimeCancelAccountOidc(): string

export declare function runtimeStartAccountVerification(payloadJson: string): string

export declare function runtimePollAccountAction(): string

export declare function runtimeAccountLogout(): string

export declare function runtimeCancelAccountChallenge(): string

export declare function runtimeStartAddressBookSync(): string

export declare function runtimePollAddressBookSync(): string

export declare function runtimeGetDecoderCapabilities(): string

export declare function runtimeGetServerConfig(): string

export declare function runtimeInit(appDir: string, deviceName: string): string

export declare function runtimeListAddressBookPeers(): string

export declare function runtimeListFavorites(): string

export declare function runtimeListLanPeers(): string

export declare function runtimeListLocalDir(path: string): string

export declare function runtimeListRecentPeers(): string

export declare function runtimeQueryPeerOnlineStates(peerIdsJson: string): Promise<string>

export declare function runtimeProbePeerDirectStates(targetsJson: string): Promise<string>

export declare function runtimeRemoveRecentPeer(peerId: string): string

export declare function runtimeScanLanPeers(): string

export declare function runtimeSetFavorite(peerId: string, favorite: boolean): string

export declare function runtimeSetServerConfig(configJson: string): string

export declare function runtimeTestServerConfig(configJson: string): Promise<string>

export declare function sessionAdd(sessionId: string, peerTarget: string, optionsJson: string): string

export declare function sessionAlternativeCodecs(sessionId: string): string

export declare function sessionBindSurface(sessionId: string, display: number, surfaceId: string): string

export declare function sessionCancelJob(sessionId: string, actId: number): string

export declare function sessionChangeResolution(sessionId: string, display: number, width: number, height: number): string

export declare function sessionClose(sessionId: string): string

export declare function sessionEnterOrLeave(sessionId: string, enter: boolean): string

export declare function sessionGetAuditGuid(sessionId: string): string

export declare function sessionGetAuditServerSync(sessionId: string, typ: string): string

export declare function sessionGetCommon(sessionId: string, key: string, param: string): string | null

export declare function sessionGetCommonSync(sessionId: string, key: string, param: string): string | null

export declare function sessionGetConnSessionId(sessionId: string): string

export declare function sessionGetConnToken(sessionId: string): string | null

export declare function sessionGetCustomImageQuality(sessionId: string): Array<number> | null

export declare function sessionGetDisplaysAsIndividualWindows(sessionId: string): string | null

export declare function sessionGetEdgeScrollEdgeThickness(sessionId: string): number | null

export declare function sessionGetEnableTrustedDevices(sessionId: string): boolean

export declare function sessionGetFlutterOption(sessionId: string, key: string): string | null

export declare function sessionGetImageQuality(sessionId: string): string | null

export declare function sessionGetIsRecording(sessionId: string): boolean

export declare function sessionGetKeyboardMode(sessionId: string): string | null

export declare function sessionGetLastAuditNote(sessionId: string): string

export declare function sessionGetOption(sessionId: string, arg: string): string | null

export declare function sessionGetPeerOption(sessionId: string, name: string): string

export declare function sessionGetRemember(sessionId: string): boolean | null

export declare function sessionGetRenderStats(sessionId: string, display: number): string

export declare function sessionGetRemoteAudioState(sessionId: string): string

export declare function sessionGetReverseMouseWheelSync(sessionId: string): string | null

export declare function sessionGetRgbaSize(sessionId: string, display: number): number

export declare function sessionGetScrollStyle(sessionId: string): string | null

export declare function sessionGetToggleOption(sessionId: string, arg: string): boolean

export declare function sessionGetTrackpadSpeed(sessionId: string): number | null

export declare function sessionGetUseAllMyDisplaysForTheRemoteSession(sessionId: string): string | null

export declare function sessionGetViewStyle(sessionId: string): string | null

export declare function sessionHandleFlutterKeyEvent(sessionId: string, keyJson: string): string

export declare function sessionInputKey(sessionId: string, keyJson: string): string

export declare function sessionInputString(sessionId: string, value: string): string

export declare function sessionIsKeyboardModeSupported(sessionId: string, mode: string): boolean

export declare function sessionLogin(sessionId: string, loginJson: string): string

export declare function sessionNextRgba(sessionId: string, display: number): void

export declare function sessionOnWaitingForImageDialogShow(sessionId: string): string

export declare function sessionPeerOption(sessionId: string, name: string, value: string): void

export declare function sessionPollEvents(sessionId: string, limit: number): string

export declare function sessionReadRemoteDir(sessionId: string, path: string, includeHidden: boolean): string

export declare function sessionReconnect(sessionId: string, forceRelay: boolean): string

export declare function sessionRefresh(sessionId: string, display: number): string

export declare function sessionSend2Fa(sessionId: string, code: string, trustThisDevice: boolean): string

export declare function sessionSendChat(sessionId: string, text: string): string

export declare function sessionSendClipboard(sessionId: string, content: string): string

export declare function sessionSendFiles(sessionId: string, actId: number, path: string, to: string, fileNum: number, includeHidden: boolean, isRemote: boolean, isDir: boolean): string

export declare function sessionSendMouse(sessionId: string, mouseJson: string): string

export declare function sessionSendNote(sessionId: string, note: string): void

export declare function sessionSendPointer(sessionId: string, pointerJson: string): string

export declare function sessionSetAuditGuid(sessionId: string, guid: string): void

export declare function sessionSetCodecPreference(sessionId: string, codec: string): string

export declare function sessionSetCommon(sessionId: string, key: string, value: string): void

export declare function sessionSetConfirmOverrideFile(sessionId: string, actId: number, fileNum: number, needOverride: boolean, remember: boolean, isUpload: boolean): string

export declare function sessionSetCustomFps(sessionId: string, fps: number): string

export declare function sessionSetCustomImageQuality(sessionId: string, value: number): void

export declare function sessionSetDisplaysAsIndividualWindows(sessionId: string, value: string): void

export declare function sessionSetEdgeScrollEdgeThickness(sessionId: string, value: number): void

export declare function sessionSetFlutterOption(sessionId: string, key: string, value: string): void

export declare function sessionSetImageQuality(sessionId: string, value: string): string

export declare function sessionSetKeyboardMode(sessionId: string, value: string): void

export declare function sessionSetReverseMouseWheel(sessionId: string, value: string): void

export declare function sessionSetScrollStyle(sessionId: string, value: string): void

export declare function sessionSetShowRemoteCursor(sessionId: string, enabled: boolean): string

export declare function sessionSetSize(sessionId: string, display: number, width: number, height: number): string

export declare function sessionSetTrackpadSpeed(sessionId: string, value: number): void

export declare function sessionSetUseAllMyDisplaysForTheRemoteSession(sessionId: string, value: string): void

export declare function sessionSetViewStyle(sessionId: string, value: string): void

export declare function sessionStart(sessionId: string): string

export declare function sessionSetViewOnly(sessionId: string, enabled: boolean): string

export declare function sessionSwitchDisplay(sessionId: string, displaysJson: string): string

export declare function sessionTakeRgbaFrame(sessionId: string, display: number): Uint8Array

export declare function sessionToggleOption(sessionId: string, arg: string): void

export declare function transferNextJobId(): number
